Added basic components
Makeam/react-blog pull request #1
Opened 2017-01-07 14:05 UTC by Makeam

2017-01-09 15:27 UTC, index01d requested changes

2017-01-09 15:27 UTC, index01d commented on components/ui/BlogItem.js
> +        [
лучше передать без массива, как несколько элементов (тогда не потребуется формировать атрибут key, иначе будет получен warning).

2017-01-09 15:27 UTC, index01d commented on components/ui/ImageBox.js
> +            , src: img.src
префиксную запятую использовать лучше только для передачи элементов. Но это субъективно.

2017-01-18 09:23 UTC, Makeam commented
Исправил.

2017-01-20 06:13 UTC, index01d approved these changes

2017-04-03 06:10 UTC, merged