Lessons 02-03-04
Makeam/react-blog pull request #2
Opened 2017-03-27 09:45 UTC by Makeam

2017-03-27 10:49 UTC, index01d requested changes
Попробуй вызвать в терминале ./node_modules/eslint/bin/eslint.js src/. Нужно удостовериться в том, что нет ошибок

2017-03-27 10:49 UTC, index01d commented on src/components/containers/BlogPage.js
> +import BlogList from '../ui/BlogList';
лучше использовать абсолютные пути (components/ui/BlogList)

2017-03-27 10:49 UTC, index01d commented on src/components/containers/BlogPage.js
> +import _ from 'lodash';
Нужно импортировать конкретные функции из библиотеки (import { find } from 'lodash')

2017-03-27 10:49 UTC, index01d commented on src/components/containers/BlogPage.js
> +      item.meta.likesCount += 1;
здесь только что было изменено содержимое состояния без вызова функции setState, нужно исправить (тк это противоречит правилам использования состояния и данные теоретически могут быть потеряны).

2017-03-27 10:49 UTC, index01d commented on src/components/containers/BlogPage.js
> +    console.log(itemId);
нужно прибрать все вызовы console.log

2017-03-27 10:49 UTC, index01d commented on webpack.config.js
> +            // {
Почему закоментировано?

2017-03-27 10:49 UTC, index01d commented on webpack.config.js
> +        // root: root
нужно раскомментировать, чтобы использовать абсолютные пути в import

2017-03-28 08:10 UTC, Makeam commented on webpack.config.js
> +        // root: root
Раскомментировал и вспомнил, что я поставил webpack 2.. и эта опция оказалась устаревшей..  перенастроил конфиг, как положено. Но остальное пока не исправил. Залью всё вместе.

2017-03-28 16:08 UTC, index01d commented on webpack.config.js
> +        // root: root
webpack 2 то я и не заметил, да. Ну хорошо, раз справился. Мигни, как нужно будет проверить все вместе.

2017-03-29 06:07 UTC, Makeam commented
Вроде всё поправил. Eslint показывает одну ошибку, (неиспользуемое свойство width) пока оставил сознательно, потом либо удалю. либо использую :).
Правильно ли я понимаю, что никак нельзя обновить в state только один измененный элемент массива? потому что он (элемент) не является отдельным свойством объекта.
Т. е. для изменения элемента массива всегда нужно создавать полную копию массива и передавать в state?

2017-03-30 13:08 UTC, index01d commented
почти так. Чуть более подробную информацию можно найти по ссылкам:
https://facebook.github.io/react/docs/update.html
и
https://github.com/kolodny/immutability-helper

2017-03-30 13:12 UTC, index01d approved these changes

2017-03-30 13:12 UTC, index01d commented on src/components/containers/BlogPage.js
> +        return i;
если так, то вернуть i

2017-03-30 13:12 UTC, index01d commented on src/components/containers/BlogPage.js
> +        return i;
а если нет, то тоже вернуть. Придираюсь конечно, но все же:)

2017-03-30 13:12 UTC, index01d commented on src/components/ui/BlogList.js
> +import _ from 'lodash';
лучше импортировать конкретные функции из библиотеки lodash

`import { map } from 'lodash/collection'`

2017-03-31 06:12 UTC, Makeam commented
Исправил. :)  
Для чего нужно указывать '.../collection'? Быстрее импорт происходит? 
'lodash' ведь тоже работает.

2017-03-31 06:23 UTC, Makeam commented
И на счет иммутабилити хелпера..

Я попробовал переписать код с его использованием.. 
Код получился не очень компактным из-за вложенности свойств. Ну это ладно..
Главное - у меня НЕ получилось обратиться к нужному элементу.
если я явно укажу ```{2: {meta:{likesCount...``` , то всё работает _(но естественно меняет счетчик только у элемента с индексом 2.)_ а вот динамически указать этот индекс не получается. 
Я так понимаю что функция пытается найти свойство id.
С ```{itemId:{meta:...```  тоже не работает. 

```javascript
  incrementLikesCount(itemId) {
    let id = itemId; // добавил чтобы явно указать что это переменная.
    const newItems = update(
      this.state.items, 
      {id: {meta:{likesCount:{$apply: function(x) {return x ? x + 1 : 1;}}}}} 
    );
    this.setState({items: newItems});
  }
 ```

2017-03-31 08:53 UTC, Makeam commented
В консоли обнаружил.. 
Warning: Failed prop type: Property `items` of component `BlogList` has **invalid PropType notation** inside arrayOf.

Посмотри, пожалуйста, что там неправильно..  вроде все там логично :)

2017-03-31 08:59 UTC, Makeam commented
И ещё.. получается что в мне нужно запоминать и передавать не **id** записи.. а **индекс** записи внутри массива. (ведь в реальности id не идут по порядку (удаленные записи, сортировки и т.п.) а индексы всегда по порядку).
Соответственно это ещё одно дополнительное свойство, которое нужно учитывать и передавать. И теперь кажется что лучше было оставить  ```map.(...```
:)

2017-04-01 10:38 UTC, index01d commented
> Для чего нужно указывать '.../collection'? Быстрее импорт происходит?
'lodash' ведь тоже работает.

При дальнейшей настройке можно будет сократить размер итогового bundle-файла приложения

> В консоли обнаружил..

arrayOf принимает в качестве параметра 1 тип., поэтому ты можешь указать в качестве аргумента ему например:
```
items: React.PropTypes.arrayOf(React.PropTypes.oneOfType([image, text, meta]))
```

> И ещё.. получается что в мне нужно запоминать и передавать не id записи.. а индекс записи внутри массива. (ведь в реальности id не идут по порядку (удаленные записи, сортировки и т.п.) а индексы всегда по порядку).
Соответственно это ещё одно дополнительное свойство, которое нужно учитывать и передавать. И теперь кажется что лучше было оставить map.(...

Если речь идет о списке постов, то передавать в качестве key нужно именно id записи. Так как в ином случае (при указания порядкового номера), React будет считать карточку записи относящейся к одной и той же записи и будет весьма некорректно ее перерисовывать (чуть заметно, но будет выглядеть будто карточки не меняются, а превращаются из предыдущего поста в текущий).

2017-04-03 06:10 UTC, merged