Les 05
Makeam/react-blog pull request #3
Opened 2017-04-18 07:51 UTC by Makeam

Сделал по минимуму..  дополнитеные задания чувствую не успеть мне..
Вопрос:
Я бы хотел чтобы в списке постов текст был ссылкой, а в том же компоненте но на странице поста ссылка уже не нужна.  Как это лучше сделать?
Как определить на какой странице смонтирован компонент?
А если я захочу на странице Поста в правой колонке показать другие посты.. 
Просто параметром передавать?  

Хотя в реальном проекте это скорее всего будут разные компоненты :)

2017-04-18 17:41 UTC, index01d requested changes

2017-04-18 17:41 UTC, index01d commented on src/components/containers/BlogPage.js
> +      .get('http://localhost:3001/posts')
хост лучше уносить в константы

2017-04-18 17:41 UTC, index01d commented on src/constants/blog_config.js
> +export const API_SERVER_PATH = 'http://localhost:3001';
почему-то в названии файла не camelCase

2017-04-18 17:41 UTC, index01d commented on src/components/ui/BlogItem.js
> +          <Link to={postPath(id)}>
Лучше в контейнерном компоненте пробежаться по записям и сгенерировать url там, тогда презентационные компоненты не будут зависеть от роутерной логики

2017-04-18 17:45 UTC, index01d commented
> Я бы хотел чтобы в списке постов текст был ссылкой, а в том же компоненте но на странице поста ссылка уже не нужна. Как это лучше сделать?

Можно использовать свойство activeClassName у компонента Link и навешивать специальный класс. Либо передавать свойство для BlogItem компонента и сделать условный рендеринг (даже такое кривое на вид решение лучше чем проверка текущего роута/URL).

> Как определить на какой странице смонтирован компонент?

Компонент, который рендерит роутер получает специальные свойства, в том числе location-объект. Лучше использовать эти свойства по минимуму и в данном кейсе точно лучше избегать их использования.

> А если я захочу на странице Поста в правой колонке показать другие посты..
Просто параметром передавать?

Представление страницы поста должно тогда отображать BlogItem и колонку с другими постами. Здесь нужно просто разделять представление страницы поста от компонента поста.

2017-04-19 06:54 UTC, Makeam commented
Поправил.

2017-04-19 06:55 UTC, Makeam commented on src/constants/blog_config.js
> +export const API_SERVER_PATH = 'http://localhost:3001';
ruby style прорвался (:

2017-04-19 07:06 UTC, index01d requested changes

2017-04-19 07:06 UTC, index01d commented on src/components/ui/BlogList.js
> +    let post_url = postPath(item.id);
camelCase:)

2017-04-19 07:06 UTC, index01d commented on src/components/ui/BlogList.js
>      i += 1;
функция map передает индекс элемента в параметре коллбэку, то есть можно написать (item, index) => и использовать индекс. Но лучше завести поле id для записей

2017-04-19 07:06 UTC, index01d commented on src/components/ui/BlogList.js
>      i += 1;
точнее поле как я вижу уже есть и не совсем ясно зачем тогда для лайка используется индекс в массиве

2017-04-19 07:06 UTC, index01d commented on src/components/ui/BlogList.js
> +          post_url
к тому же свойство у BlogItem называется по-другому и непохоже на то, чтобы это должно было работать

2017-04-19 08:20 UTC, Makeam commented on src/components/ui/BlogList.js
> +          post_url
Всё работает корректно, потому что я ищу элемент именно по индексу в массиве.
```
incrementLikesCount(itemId) {
    const newItems = update(
      this.state.items,
      {[itemId]: {meta: {likesCount: { $apply: function(x) { return x ? x + 1 : 1; }}}}}
    );
    this.setState({items: newItems});
 }
```

Я в принципе понимаю что это как-то не совсем логично. 
И я даже думал исправить это.. Но времени катастрофически мало. 
Давай пообещаю подумать и исправить. Но не в этой итерации.. (:

2017-04-19 08:21 UTC, Makeam commented on src/components/ui/BlogList.js
> +    let post_url = postPath(item.id);
мда..  я все таки постоянно на ruby пишу..   стоит чуть отвлечься руки сами переходят на "underscore_case" (:

2017-05-03 06:43 UTC, merged